version: '3.0'

services:
  db:
    image: postgres:16
    container_name: postgres
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_DEFAULT_USER}
      POSTGRES_PASSWORD: ${DATABASE_ROOT_PASSWORD}
    ports:
      - 5432:5432
    volumes:
      - database_volume:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:8
    container_name: pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}

volumes:
  database_volume:

networks:
  api_network:
    driver: bridge
